services:
  postgres:
    image: postgres:17
    container_name: chamados-postgres
    environment:
      POSTGRES_DB: chamados
      POSTGRES_USER: chamados
      POSTGRES_PASSWORD: chamados
    ports:
      - "5432:5432" 
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend